version: "3"
services:
  gui:
    build: ./
    image: "theophile/cos-api-gui"
    ports:
      - '3000:3000'
    command: "npm run startGui"

  api:
    build: ./
    image: "theophile/cos-api-gui"
    ports:
      - '3001:3001'
    command: "npm run startApi "
  mongodb:
    image: mongo
    ports:
      - '27017:27017'